config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit'
  patch 'tasks/:id', to: 'tasks#update'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to task_path(task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :detail, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
render 

app/views/tasks/edit.html.erb
<%= form_with model: @task do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :detail %>
  <%= t.text_field :detail %>
  <%= t.submit %>
<% end %>

app/views/tasks/index.html.erb
<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task[:id]) %></li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<%= form_with model: @task do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :detail %>
  <%= t.text_field :detail %>
  <%= t.submit %>
<% end %>

## pe render 'form' 

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.detail %></p>
<p><%= @task.completed %></p>
<p><%= link_to 'Back to list', tasks_path  %></p>